# 用于训练的分辨率，给定为方形图像的边长。您可以在此处设置多个尺寸。  24g显存最大只能跑512*512
resolutions = [512]
# 您也可以以 (宽度, 高度) 的形式给出分辨率。这并没有任何不同，只是
# 另一种指定您想要训练的面积（即像素总数）的方式。
# resolutions = [[1280, 720]]

# 启用长宽比分桶。对于不同的长宽比桶，最终的尺寸将是
# 面积匹配您上面配置的分辨率。
enable_ar_bucket = true

# 每个“[[directory]]”条目也可以指定长宽比和帧桶设置。
# 目录级别的设置将覆盖顶级设置。

# 最小和最大长宽比，以宽度/高度的比例给出。
min_ar = 0.5
max_ar = 2.0
# 长宽比桶的总数，在 min_ar 和 max_ar 之间均匀分布（在对数空间中）。
num_ar_buckets = 7

# 可以手动指定 ar_buckets 而不是使用上述范围样式配置。
# 每个条目可以是宽度/高度比，也可以是 (宽度, 高度) 对。但由于 TOML 的特性，您不能混合使用。
# ar_buckets = [[512, 512], [448, 576]]
# ar_buckets = [1.0, 1.5]

# 高级的，输入框输入：1,2,3
# 对于视频训练，您需要配置帧桶（类似于长宽比桶）。对于图像，总是会有一个帧桶为 1。视频将被分配到第一个长度
# 大于或等于的帧桶。但是，视频永远不会被分配到图像帧桶（1）；如果视频非常短，它将被丢弃。
frame_buckets = [1, 33, 65]

[[directory]]
# 图像/视频目录及其对应的字幕文件路径。字幕文件应与媒体文件名匹配，但扩展名为 .txt。
# 缺少字幕文件将记录一个警告，但将使用空字幕进行训练。
path = '/home/anon/data/images/grayscale'
# 数据集将像被重复这么多次一样进行操作。
num_repeats = 10
# 示例覆盖某些设置，并使用 ar_buckets 直接指定长宽比。
# ar_buckets = [[448, 576]]
# resolutions = [[448, 576]]
# frame_buckets = [1]

# 您可以列出多个目录。

# [[directory]]
# path = '/home/anon/data/images/something_else'
# num_repeats = 5
